# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8831255445394f6f206a96f47c419ee85b9b384c3876311bdeada9244ef951beed5700056c3562358de79da9a7ca6d4c0422ae5899dd4dd2d6bb05ad11ca3c3

test:
  secret_key_base: aa7935ef6490f91eb9617df42edd5183ada9a1520157c9aa6635565df69f0cdc5df99d38d4225b36342fcd50978d911a90abe83cc641835deb0a8f6e47ae90d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
